ls;
count /;
insert element foo into /*;
count count(//foo)>0;
$bar=0;
count $bar=0;
while count(//foo)<10 { insert element "<foo bar='$bar\' count=${{count(//foo)}}" into /*; $bar=$bar+1 };
count count(//foo)=10;
count count(//foo[@bar="8"])=1;
count count(//foo[@count and @bar=string(@count)-1])>0;
perl { 1+1; };
exec ls -l;
clone t=scratch;
def myfunc { defs; encoding iso-8859-2; };
call myfunc;
files;
foreach scratch://foo { insert text "no. " into .; copy ./@bar after ./text() };
indent 1;
